# Don't forget you can override this file in
# app/Resources/PlivoBundle/validation/Model.SmsIncoming.yml
Plivo\Model\SmsIncoming:
  properties:
    from:
      - NotBlank: ~
      - Type: string
    to:
      - NotBlank: ~
      - Type: string
    text:
      - NotBlank: ~
      - Type: string
