# Don't forget you can override this file in
# app/Resources/FLPlivoBundle/validation/Model.SmsOutgoing.yml
Plivo\Model\SmsOutgoing:
    properties:
        from:
            - NotBlank: ~
            - Type: string
            - Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber:
                type: "mobile"
        to:
            - NotBlank: ~
            - Type: string
            - Expression:
                expression: "this.getFrom() !== this.getTo()"
                message: "From and To cannot be the same"
        text:
            - NotBlank: ~
            - Type: string
