# Don't forget you can override this file in
# app/Resources/FLPlivoBundle/validation/Model.BulkSmsOutgoing.yml
Plivo\Model\BulkSmsOutgoing:
    constraints:
      - FL\PlivoBundle\Validator\Constraint\FromCountry:
          fromField: from
          toField: to
          errorPath: to

    properties:
        from:
            - NotBlank: ~
            - Type: string
        to:
            - All:
                - NotBlank: ~
                - Type: string
                - Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber:
                    type: "mobile"
                    message: "All phone numbers must be valid."
            - Expression:
                expression: "this.getFrom() not in this.getTo()"
                message: "From and To cannot contain the same number."
        text:
            - NotBlank: ~
            - Type: string
